AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false