production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>

development:
  adapter: postgis
  postgis_extension: postgis
  postgis_schema: public          
  url: <%= ENV["DATABASE_URL"] %>

test:
  adapter: postgis
  url: <%= ENV["DATABASE_URL_TEST"] %>