production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || 5 %>

development:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>

test:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL_TEST"] %>